import type { PtkgNode, PtkgSource } from '../types.ts';

export const STARRYOS_SHARED_SOURCES: PtkgSource[] = [
  {
    id: 'src.axfs-ng-vfs',
    type: 'source',
    source_kind: 'repo_file',
    title: 'Starry-OS/axfs-ng-vfs - StarryOS VFS traits',
    url: 'https://github.com/Starry-OS/axfs-ng-vfs/tree/c405647560bcd31eab915b47f06d148e88578d0b',
    retrieved_at: '2026-07-26',
    version_or_ref: 'c405647560bcd31eab915b47f06d148e88578d0b',
    trust_level: 'A',
    supports: ['StarryOS 使用 NodeOps、DirNodeOps 和 FileNodeOps，而不是经典 axfs_vfs traits'],
  },
  {
    id: 'src.canonical.qemu-system-emulation',
    type: 'source',
    source_kind: 'official_spec',
    title: 'QEMU system emulation documentation',
    url: 'https://www.qemu.org/docs/master/system/index.html',
    retrieved_at: '2026-08-07',
    version_or_ref: null,
    trust_level: 'A',
    supports: ['固定机器、CPU、内存与镜像参数是可重放系统实验的基础'],
  },
  {
    id: 'src.canonical.rust-no-std',
    type: 'source',
    source_kind: 'official_spec',
    title: 'Rust Reference: the no_std attribute',
    url: 'https://doc.rust-lang.org/reference/names/preludes.html#the-no_std-attribute',
    retrieved_at: '2026-08-07',
    version_or_ref: null,
    trust_level: 'A',
    supports: ['no_std crate 不链接 std，并使用 core prelude'],
  },
  {
    id: 'src.canonical.linux-process-lifecycle',
    type: 'source',
    source_kind: 'man_page',
    title: 'Linux man-pages: process lifecycle interfaces',
    url: 'https://man7.org/linux/man-pages/man2/clone.2.html',
    retrieved_at: '2026-08-07',
    version_or_ref: null,
    trust_level: 'A',
    supports: ['进程创建、资源共享、退出和等待共同构成生命周期合同'],
  },
  {
    id: 'src.canonical.rust-atomics-locks',
    type: 'source',
    source_kind: 'official_spec',
    title: 'Rust core::sync::atomic documentation',
    url: 'https://doc.rust-lang.org/core/sync/atomic/',
    retrieved_at: '2026-08-07',
    version_or_ref: null,
    trust_level: 'A',
    supports: ['并发正确性需要明确原子顺序、锁保护范围和资源生命周期'],
  },
  {
    id: 'src.canonical.kernel-selftests',
    type: 'source',
    source_kind: 'kernel_doc',
    title: 'Linux kernel selftests documentation',
    url: 'https://docs.kernel.org/dev-tools/kselftest.html',
    retrieved_at: '2026-08-07',
    version_or_ref: null,
    trust_level: 'A',
    supports: ['内核行为需要正例、负例、并发与回归证据，而不是只看一次成功输出'],
  },
];

export const STARRYOS_SHARED_NODES: PtkgNode[] = [
  {
    id: 'kc.os.build.reproducible-qemu',
    type: 'knowledge',
    scope: 'canonical',
    title: '固定源码与 QEMU 可重放构建',
    status: 'candidate',
    statement: '学生能够锁定 commit/tree、工具链与 QEMU 参数，复现构建和启动并保存可核验的环境、命令与日志证据。',
    difficulty: { prerequisite_depth: 1, subsystem_span: 2, concurrency: 0, source_maturity: 3 },
    misconceptions: ['把当前分支名或一次成功截图当成可重放基线'],
    diagnostic: '给出只有 branch 和截图的构建记录，指出无法重放的字段。',
    remediation: ['补齐 commit/tree、工具链版本、QEMU 参数、stdout/stderr 和退出码。'],
    source_ids: ['src.canonical.qemu-system-emulation'],
    tags: ['os', 'build', 'qemu', 'shared-trunk'],
  },
  {
    id: 'kc.rust.no-std.kernel-boundaries',
    type: 'knowledge',
    scope: 'canonical',
    title: 'Rust no_std 内核边界',
    status: 'candidate',
    statement: '学生能够在 no_std 环境中区分 core/alloc 与宿主 std 能力，识别初始化、分配、panic 和平台依赖的边界。',
    difficulty: { prerequisite_depth: 2, subsystem_span: 2, concurrency: 1, source_maturity: 3 },
    misconceptions: ['把宿主 Rust 示例直接复制进内核并假设 std 可用'],
    diagnostic: '判断一段依赖 std::sync 和文件系统的代码能否直接进入 no_std 内核。',
    remediation: ['列出 core/alloc 替代项以及必须由平台注入的能力。'],
    source_ids: ['src.canonical.rust-no-std'],
    tags: ['rust', 'no-std', 'shared-trunk'],
  },
  {
    id: 'kc.os.process.lifecycle',
    type: 'knowledge',
    scope: 'canonical',
    title: '进程创建、执行、退出与回收生命周期',
    status: 'candidate',
    statement: '学生能够沿创建、exec、退出、wait 和资源回收追踪进程生命周期，并解释错误与并发路径上的不变量。',
    difficulty: { prerequisite_depth: 2, subsystem_span: 3, concurrency: 2, source_maturity: 3 },
    misconceptions: ['只看 fork 成功路径，忽略失败回滚、退出通知和资源归还'],
    diagnostic: '给出创建后初始化失败的路径，列出必须回滚的资源。',
    remediation: ['画出 create/exec/exit/wait 状态转换和所有权表。'],
    source_ids: ['src.canonical.linux-process-lifecycle'],
    tags: ['os', 'process', 'lifecycle', 'shared-trunk'],
  },
  {
    id: 'kc.os.vfs.axfs-ng-vfs-traits',
    type: 'knowledge',
    scope: 'canonical',
    title: 'axfs-ng-vfs 的 NodeOps / DirNodeOps / FileNodeOps',
    status: 'candidate',
    statement: '学生能够说明 StarryOS 伪文件系统使用的 VFS trait 及其与 ArceOS unikernel 侧 axfs_vfs 的区别，并指出目录与接口文件各实现哪一套。',
    difficulty: { prerequisite_depth: 2, subsystem_span: 2, concurrency: 1, source_maturity: 3 },
    misconceptions: ['按 ArceOS 经典 axfs_vfs 的 VfsOps / VfsNodeOps 设计 StarryOS 文件系统，导致代码无法编译'],
    diagnostic: '给出目录与文件对象，判断应实现 NodeOps、DirNodeOps 还是 FileNodeOps。',
    remediation: ['对照 axfs-ng-vfs 的 trait 定义和 StarryOS pseudofs 实现。'],
    source_ids: ['src.axfs-ng-vfs'],
    tags: ['os', 'vfs', 'starryos', 'shared-trunk'],
  },
  {
    id: 'kc.os.concurrency.lock-and-lifetime',
    type: 'knowledge',
    scope: 'canonical',
    title: '锁、原子操作与资源生命周期不变量',
    status: 'candidate',
    statement: '学生能够标注共享状态、锁序、原子操作和资源获取释放边界，并用并发与失败注入证明不死锁、不泄漏。',
    difficulty: { prerequisite_depth: 3, subsystem_span: 3, concurrency: 3, source_maturity: 3 },
    misconceptions: ['看到 Rust 类型安全就假设跨子系统并发不变量自动成立'],
    diagnostic: '为一条同时持有任务锁和文件锁的路径标注潜在锁序反转。',
    remediation: ['建立锁序表、所有权表和失败回滚检查表。'],
    source_ids: ['src.canonical.rust-atomics-locks'],
    tags: ['os', 'concurrency', 'lifetime', 'shared-trunk'],
  },
  {
    id: 'kc.os.testing.four-way-evidence',
    type: 'knowledge',
    scope: 'canonical',
    title: '正例、负例、并发与回归四类工程证据',
    status: 'candidate',
    statement: '学生能够根据行为合同设计正例、负例、并发和回归测试，并区分测试设计、真实执行与教师确认三种证据状态。',
    difficulty: { prerequisite_depth: 2, subsystem_span: 2, concurrency: 2, source_maturity: 3 },
    misconceptions: ['把一条 happy-path 日志或 AI 评价当成工程能力证据'],
    diagnostic: '判断只覆盖成功返回的测试为什么无法识别绕过校验的 seeded fault。',
    remediation: ['为同一行为补齐非法输入、竞争和既有行为保持测试。'],
    source_ids: ['src.canonical.kernel-selftests'],
    tags: ['os', 'testing', 'evidence', 'shared-trunk'],
  },
];
